#!/bin/bash

####################################
#
# Backup Document dir script.
#
####################################

# Instruction
<< 'INSTRUCTION-COMMENT'
    A bash script that backups the Document directory as an archive file and saves it to the backup dir
    
    N/B: To backup other directories, just change your desired file paths in the "BACKUP_PATH" variable

    Running installation:
    - From terminal run:
        `./install`

INSTRUCTION-COMMENT

#TODO: What to backup.
BACKUP_PATH="$HOME/Documents"

# create a directory "backup"
mkdir $HOME/backup
#TODO: Where to backup to.
DEST_PATH="$HOME/backup/"

#TODO: Create archive filename.

DATE=`date +%d%m%Y`
BACKUP="doc_"
EXT=".tar"
FILE_NAME=$DEST_PATH$BACKUP$DATE$EXT

# Print start status message.
echo "Hey $USER, Backing up $BACKUP_PATH to $FILE_NAME"
date
echo

# Backup the files using tar.

tar cfz $FILE_NAME $BACKUP_PATH

# Print end stataus message
echo
echo "Backup finished"
date

# Long listing of files in $dest to check file sizes.
ls -lh $FILE_NAME 